# Generated by Django 4.1.5 on 2023-01-14 16:10

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="",
                        validators=[
                            app.models.file_size,
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            ),
                        ],
                    ),
                ),
                ("session", models.CharField(max_length=150)),
                ("edited", models.BooleanField(default=False)),
                (
                    "prepared_for",
                    models.CharField(
                        choices=[
                            ("australia_passport", "Australia Passport"),
                            ("canada_passport", "Canada Passport"),
                            ("canada_visa", "Canada Visa"),
                            ("china_visa", "China Visa"),
                            ("european_union_passport", "European Union Passport"),
                            ("japan_visa", "Japan Visa"),
                            ("india_visa", "India Visa"),
                            ("schengen_visa", "Schengen Visa"),
                            ("us_visa", "US Visa"),
                            ("us_passport", "US Passport"),
                        ],
                        max_length=50,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
