# Generated by Django 4.1.5 on 2023-01-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_file_owner_alter_file_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="owner",
            field=models.CharField(max_length=140),
        ),
    ]
