# Generated by Django 4.1.5 on 2023-01-09 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_file_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="owner",
        ),
    ]
