# Generated by Django 4.1.5 on 2023-01-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_file_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="name",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
