# Generated by Django 4.1.5 on 2023-01-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_file_prepared_for_alter_file_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="file",
            name="prepared_for",
            field=models.CharField(
                choices=[
                    ("australia_passport", "Australia Passport"),
                    ("canada_passport", "Canada Passport"),
                    ("canada_visa", "Canada Visa"),
                    ("china_visa", "China Visa"),
                    ("european_union_passport", "European Union Passport"),
                    ("japan_visa", "Japan Visa"),
                    ("india_visa", "India Visa"),
                    ("schengen_visa", "Schengen Visa"),
                    ("us_visa", "US Visa"),
                    ("us_passport", "US Passport"),
                ],
                max_length=50,
            ),
        ),
    ]
