# Generated by Django 4.1.5 on 2023-01-11 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_file_edited_alter_file_prepared_for"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="File",
            new_name="UserFile",
        ),
    ]
